export const categoriesJson = [
  {
    id: 1,
    name: 'Electronics',
    subcategories: [
      { id: 101, name: 'Accessories & Supplies' },
      { id: 102, name: 'Camera & Photo' },
      { id: 103, name: 'Car & Vehicle Electronics' },
      { id: 104, name: 'Cell Phones & Accessories' },
      { id: 105, name: 'Computers & Accessories' },
      { id: 106, name: 'GPS & Navigation' },
      { id: 107, name: 'Headphones' },
      { id: 108, name: 'Home Audio' },
      { id: 109, name: 'Office Electronics' },
      { id: 110, name: 'Portable Audio & Video' },
      { id: 111, name: 'Security & Surveillance' },
      { id: 112, name: 'Service Plans' },
      { id: 113, name: 'Television & Video' },
      { id: 114, name: 'Video Game Consoles & Accessories' },
      { id: 115, name: 'Video Projectors' },
      { id: 116, name: 'Wearable Technology' },
      { id: 117, name: 'eBook Readers & Accessories' },
    ],
  },
  {
    id: 2,
    name: 'Computers',
    subcategories: [
      { id: 201, name: 'Computer Accessories & Peripherals' },
      { id: 202, name: 'Computer Components' },
      { id: 203, name: 'Computers & Tablets' },
      { id: 204, name: 'Data Storage' },
      { id: 205, name: 'External Components' },
      { id: 206, name: 'Laptop Accessories' },
      { id: 207, name: 'Monitors' },
      { id: 208, name: 'Networking Products' },
      { id: 209, name: 'Power Strips & Surge Protectors' },
      { id: 210, name: 'Printers' },
      { id: 211, name: 'Scanners' },
      { id: 212, name: 'Servers' },
      { id: 213, name: 'Tablet Accessories' },
      { id: 214, name: 'Tablet Replacement Parts' },
      { id: 215, name: 'Warranties & Services' },
    ],
  },
  {
    id: 3,
    name: 'Smart Home',
    subcategories: [
      { id: 301, name: 'Amazon Smart Home' },
      { id: 302, name: 'Works with Alexa Devices' },
      { id: 303, name: 'Smart Home Lighting' },
      { id: 304, name: 'Smart Locks and Entry' },
      { id: 305, name: 'Security Cameras and Systems' },
      { id: 306, name: 'Plugs and Outlets' },
      { id: 307, name: 'New Smart Devices' },
      { id: 308, name: 'Heating and Cooling' },
      { id: 309, name: 'Detectors and Sensors' },
      { id: 310, name: 'Home Entertainment' },
      { id: 311, name: 'Pet' },
      { id: 312, name: 'Voice Assistants and Hubs' },
      { id: 313, name: 'Kitchen' },
      { id: 314, name: 'Vacuums and Mops' },
      { id: 315, name: 'Lawn and Garden' },
      { id: 316, name: 'WIFI and Networking' },
      { id: 317, name: 'Other Solutions' },
    ],
  },
  {
    id: 4,
    name: 'Arts & Crafts',
    subcategories: [
      { id: 401, name: 'Painting, Drawing & Art Supplies' },
      { id: 402, name: 'Beading & Jewelry Making' },
      { id: 403, name: 'Crafting' },
      { id: 404, name: 'Fabric' },
      { id: 405, name: 'Fabric Decorating' },
      { id: 406, name: 'Knitting & Crochet' },
      { id: 407, name: 'Needlework' },
      { id: 408, name: 'Organization, Storage & Transport' },
      { id: 409, name: 'Printmaking' },
      { id: 410, name: 'Scrapbooking & Stamping' },
      { id: 411, name: 'Sewing' },
      { id: 412, name: 'Party Decorations & Supplies' },
      { id: 413, name: 'Gift Wrapping Supplies' },
    ],
  },
  {
    id: 5,
    name: 'Automotive',
    subcategories: [
      { id: 501, name: 'Car Care' },
      { id: 502, name: 'Car Electronics & Accessories' },
      { id: 503, name: 'Exterior Accessories' },
      { id: 504, name: 'Interior Accessories' },
      { id: 505, name: 'Lights & Lighting Accessories' },
      { id: 506, name: 'Motorcycle & Powersports' },
      { id: 507, name: 'Oils & Fluids' },
      { id: 508, name: 'Paint & Paint Supplies' },
      { id: 509, name: 'Performance Parts & Accessories' },
      { id: 510, name: 'Replacement Parts' },
      { id: 511, name: 'RV Parts & Accessories' },
      { id: 512, name: 'Tires & Wheels' },
      { id: 513, name: 'Tools & Equipment' },
      { id: 514, name: 'Automotive Enthusiast Merchandise' },
      { id: 515, name: 'Heavy Duty & Commercial Vehicle Equipment' },
    ],
  },
  {
    id: 6,
    name: 'Baby',
    subcategories: [
      { id: 601, name: 'Activity & Entertainment' },
      { id: 602, name: 'Apparel & Accessories' },
      { id: 603, name: 'Baby & Toddler Toys' },
      { id: 604, name: 'Baby Care' },
      { id: 605, name: 'Baby Stationery' },
      { id: 606, name: 'Car Seats & Accessories' },
      { id: 607, name: 'Diapering' },
      { id: 608, name: 'Feeding' },
      { id: 609, name: 'Gifts' },
      { id: 610, name: 'Nursery' },
      { id: 611, name: 'Potty Training' },
      { id: 612, name: 'Pregnancy & Maternity' },
      { id: 613, name: 'Safety' },
      { id: 614, name: 'Strollers & Accessories' },
      { id: 615, name: 'Travel Gear' },
    ],
  },
  {
    id: 7,
    name: 'Beauty and Personal Care',
    subcategories: [
      { id: 701, name: 'Makeup' },
      { id: 702, name: 'Skin Care' },
      { id: 703, name: 'Hair Care' },
      { id: 704, name: 'Fragrance' },
      { id: 705, name: 'Foot, Hand & Nail Care' },
      { id: 706, name: 'Tools & Accessories' },
      { id: 707, name: 'Shave & Hair Removal' },
      { id: 708, name: 'Personal Care' },
      { id: 709, name: 'Oral Care' },
    ],
  },
  {
    id: 8,
    name: "Women's Fashion",
    subcategories: [
      { id: 801, name: 'Clothing' },
      { id: 802, name: 'Shoes' },
      { id: 803, name: 'Jewelry' },
      { id: 804, name: 'Watches' },
      { id: 805, name: 'Handbags' },
      { id: 806, name: 'Accessories' },
    ],
  },
  {
    id: 9,
    name: "Men's Fashion",
    subcategories: [
      { id: 901, name: 'Clothing' },
      { id: 902, name: 'Shoes' },
      { id: 903, name: 'Watches' },
      { id: 904, name: 'Accessories' },
    ],
  },
  {
    id: 10,
    name: "Girls' Fashion",
    subcategories: [
      { id: 1001, name: 'Clothing' },
      { id: 1002, name: 'Shoes' },
      { id: 1003, name: 'Jewelry' },
      { id: 1004, name: 'Watches' },
      { id: 1005, name: 'Accessories' },
      { id: 1006, name: 'School Uniforms' },
    ],
  },
  {
    id: 11,
    name: "Boys' Fashion",
    subcategories: [
      { id: 1101, name: 'Clothing' },
      { id: 1102, name: 'Shoes' },
      { id: 1103, name: 'Jewelry' },
      { id: 1104, name: 'Watches' },
      { id: 1105, name: 'Accessories' },
      { id: 1106, name: 'School Uniforms' },
    ],
  },
  {
    id: 12,
    name: 'Health and Household',
    subcategories: [
      { id: 1201, name: 'Baby & Child Care' },
      { id: 1202, name: 'Health Care' },
      { id: 1203, name: 'Household Supplies' },
      { id: 1204, name: 'Medical Supplies & Equipment' },
      { id: 1205, name: 'Oral Care' },
      { id: 1206, name: 'Personal Care' },
      { id: 1207, name: 'Sexual Wellness' },
      { id: 1208, name: 'Sports Nutrition' },
      { id: 1209, name: 'Stationery & Gift Wrapping Supplies' },
      { id: 1210, name: 'Vision Care' },
      { id: 1211, name: 'Vitamins & Dietary Supplements' },
      { id: 1212, name: 'Wellness & Relaxation' },
    ],
  },
  {
    id: 13,
    name: 'Home and Kitchen',
    subcategories: [
      { id: 1301, name: "Kids' Home Store" },
      { id: 1302, name: 'Kitchen & Dining' },
      { id: 1303, name: 'Bedding' },
      { id: 1304, name: 'Bath' },
      { id: 1305, name: 'Furniture' },
      { id: 1306, name: 'Home Décor' },
      { id: 1307, name: 'Wall Art' },
      { id: 1308, name: 'Lighting & Ceiling Fans' },
      { id: 1309, name: 'Seasonal Décor' },
      { id: 1310, name: 'Event & Party Supplies' },
      { id: 1311, name: 'Heating, Cooling & Air Quality' },
      { id: 1312, name: 'Irons & Steamers' },
      { id: 1313, name: 'Vacuums & Floor Care' },
      { id: 1314, name: 'Storage & Organization' },
      { id: 1315, name: 'Cleaning Supplies' },
    ],
  },
  {
    id: 14,
    name: 'Industrial and Scientific',
    subcategories: [
      { id: 1401, name: 'Abrasive & Finishing Products' },
      { id: 1402, name: 'Additive Manufacturing Products' },
      { id: 1403, name: 'Commercial Door Products' },
      { id: 1404, name: 'Cutting Tools' },
      { id: 1405, name: 'Fasteners' },
      { id: 1406, name: 'Filtration' },
      { id: 1407, name: 'Food Service Equipment & Supplies' },
      { id: 1408, name: 'Hydraulics, Pneumatics & Plumbing' },
      { id: 1409, name: 'Industrial Electrical' },
      { id: 1410, name: 'Industrial Hardware' },
      { id: 1411, name: 'Industrial Power & Hand Tools' },
      { id: 1412, name: 'Janitorial & Sanitation Supplies' },
      { id: 1413, name: 'Lab & Scientific Products' },
      { id: 1414, name: 'Material Handling Products' },
      { id: 1415, name: 'Occupational Health & Safety Products' },
      { id: 1416, name: 'Packaging & Shipping Supplies' },
      { id: 1417, name: 'Power Transmission Products' },
      { id: 1418, name: 'Professional Dental Supplies' },
      { id: 1419, name: 'Professional Medical Supplies' },
      { id: 1420, name: 'Raw Materials' },
      { id: 1421, name: 'Retail Store Fixtures & Equipment' },
      { id: 1422, name: 'Robotics' },
      { id: 1423, name: 'Science Education' },
      { id: 1424, name: 'Tapes, Adhesives & Sealants' },
      { id: 1425, name: 'Test, Measure & Inspect' },
    ],
  },
  {
    name: 'Luggage',
    subcategories: [
      { name: 'Carry-ons' },
      { name: 'Backpacks' },
      { name: 'Garment bags' },
      { name: 'Travel Totes' },
      { name: 'Luggage Sets' },
      { name: 'Laptop Bags' },
      { name: 'Suitcases' },
      { name: 'Kids Luggage' },
      { name: 'Messenger Bags' },
      { name: 'Umbrellas' },
      { name: 'Duffles' },
      { name: 'Travel Accessories' },
    ],
  },
  {
    id: 15,
    name: 'Luggage',
    subcategories: [
      { id: 1501, name: 'Carry-ons' },
      { id: 1502, name: 'Backpacks' },
      { id: 1503, name: 'Garment bags' },
      { id: 1504, name: 'Travel Totes' },
      { id: 1505, name: 'Luggage Sets' },
      { id: 1506, name: 'Laptop Bags' },
      { id: 1507, name: 'Suitcases' },
      { id: 1508, name: 'Kids Luggage' },
      { id: 1509, name: 'Messenger Bags' },
      { id: 1510, name: 'Umbrellas' },
      { id: 1511, name: 'Duffles' },
      { id: 1512, name: 'Travel Accessories' },
    ],
  },
  {
    id: 16,
    name: 'Pet Supplies',
    subcategories: [
      { id: 1601, name: 'Dogs' },
      { id: 1602, name: 'Cats' },
      { id: 1603, name: 'Fish & Aquatic Pets' },
      { id: 1604, name: 'Birds' },
      { id: 1605, name: 'Horses' },
      { id: 1606, name: 'Reptiles & Amphibians' },
      { id: 1607, name: 'Small Animals' },
    ],
  },
  {
    id: 17,
    name: 'Software',
    subcategories: [
      { id: 1701, name: 'Accounting & Finance' },
      { id: 1702, name: 'Antivirus & Security' },
      { id: 1703, name: 'Business & Office' },
      { id: 1704, name: "Children's" },
      { id: 1705, name: 'Design & Illustration' },
      { id: 1706, name: 'Digital Software' },
      { id: 1707, name: 'Education & Reference' },
      { id: 1708, name: 'Games' },
      { id: 1709, name: 'Lifestyle & Hobbies' },
      { id: 1710, name: 'Music' },
      { id: 1711, name: 'Networking & Servers' },
      { id: 1712, name: 'Operating Systems' },
      { id: 1713, name: 'Photography' },
      { id: 1714, name: 'Programming & Web Development' },
      { id: 1715, name: 'Tax Preparation' },
      { id: 1716, name: 'Utilities' },
      { id: 1717, name: 'Video' },
    ],
  },
  {
    id: 18,
    name: 'Sports and Outdoors',
    subcategories: [
      { id: 1801, name: 'Sports and Outdoors' },
      { id: 1802, name: 'Outdoor Recreation' },
      { id: 1803, name: 'Sports & Fitness' },
    ],
  },
  {
    id: 19,
    name: 'Tools & Home Improvement',
    subcategories: [
      { id: 1901, name: 'Tools & Home Improvement' },
      { id: 1902, name: 'Appliances' },
      { id: 1903, name: 'Building Supplies' },
      { id: 1904, name: 'Electrical' },
      { id: 1905, name: 'Hardware' },
      { id: 1906, name: 'Kitchen & Bath Fixtures' },
      { id: 1907, name: 'Light Bulbs' },
      { id: 1908, name: 'Lighting & Ceiling Fans' },
      { id: 1909, name: 'Measuring & Layout Tools' },
      { id: 1910, name: 'Painting Supplies & Wall Treatments' },
      { id: 1911, name: 'Power & Hand Tools' },
      { id: 1912, name: 'Rough Plumbing' },
      { id: 1913, name: 'Safety & Security' },
      { id: 1914, name: 'Storage & Home Organization' },
      { id: 1915, name: 'Welding & Soldering' },
    ],
  },
  {
    id: 20,
    name: 'Toys and Games',
    subcategories: [
      { id: 2001, name: 'Action Figures & Statues' },
      { id: 2002, name: 'Arts & Crafts' },
      { id: 2003, name: 'Baby & Toddler Toys' },
      { id: 2004, name: 'Building Toys' },
      { id: 2005, name: 'Dolls & Accessories' },
      { id: 2006, name: 'Dress Up & Pretend Play' },
      { id: 2007, name: "Kids' Electronics" },
      { id: 2008, name: 'Games' },
      { id: 2009, name: 'Grown-Up Toys' },
      { id: 2010, name: 'Hobbies' },
      { id: 2011, name: "Kids' Furniture, Décor & Storage" },
      { id: 2012, name: 'Learning & Education' },
      { id: 2013, name: 'Novelty & Gag Toys' },
      { id: 2014, name: 'Party Supplies' },
      { id: 2015, name: 'Puppets' },
      { id: 2016, name: 'Puzzles' },
      { id: 2017, name: 'Sports & Outdoor Play' },
      { id: 2018, name: 'Stuffed Animals & Plush Toys' },
      { id: 2019, name: 'Toy Remote Control & Play Vehicles' },
      { id: 2020, name: 'Tricycles, Scooters & Wagons' },
    ],
  },
  {
    id: 21,
    name: 'Video Games',
    subcategories: [
      { id: 2101, name: 'Video Games' },
      { id: 2102, name: 'PlayStation 4' },
      { id: 2103, name: 'PlayStation 3' },
      { id: 2104, name: 'Xbox One' },
      { id: 2105, name: 'Xbox 360' },
      { id: 2106, name: 'Nintendo Switch' },
      { id: 2107, name: 'Wii U' },
      { id: 2108, name: 'Wii' },
      { id: 2109, name: 'PC' },
      { id: 2110, name: 'Mac' },
      { id: 2111, name: 'Nintendo 3DS & 2DS' },
      { id: 2112, name: 'Nintendo DS' },
      { id: 2113, name: 'PlayStation Vita' },
      { id: 2114, name: 'Sony PSP' },
      { id: 2115, name: 'Retro Gaming & Microconsoles' },
      { id: 2116, name: 'Accessories' },
      { id: 2117, name: 'Digital Games' },
      { id: 2118, name: 'Kids & Family' },
    ],
  },
];
