export const categoriesJson = [
  {
    name: 'Electronics',
    subcategories: [
      { name: 'Accessories & Supplies' },
      { name: 'Camera & Photo' },
      { name: 'Car & Vehicle Electronics' },
      { name: 'Cell Phones & Accessories' },
      { name: 'Computers & Accessories' },
      { name: 'GPS & Navigation' },
      { name: 'Headphones' },
      { name: 'Home Audio' },
      { name: 'Office Electronics' },
      { name: 'Portable Audio & Video' },
      { name: 'Security & Surveillance' },
      { name: 'Service Plans' },
      { name: 'Television & Video' },
      { name: 'Video Game Consoles & Accessories' },
      { name: 'Video Projectors' },
      { name: 'Wearable Technology' },
      { name: 'eBook Readers & Accessories' },
    ],
  },
  {
    name: 'Computers',
    subcategories: [
      { name: 'Computer Accessories & Peripherals' },
      { name: 'Computer Components' },
      { name: 'Computers & Tablets' },
      { name: 'Data Storage' },
      { name: 'External Components' },
      { name: 'Laptop Accessories' },
      { name: 'Monitors' },
      { name: 'Networking Products' },
      { name: 'Power Strips & Surge Protectors' },
      { name: 'Printers' },
      { name: 'Scanners' },
      { name: 'Servers' },
      { name: 'Tablet Accessories' },
      { name: 'Tablet Replacement Parts' },
      { name: 'Warranties & Services' },
    ],
  },
  {
    name: 'Smart Home',
    subcategories: [
      { name: 'Amazon Smart Home' },
      { name: 'Works with Alexa Devices' },
      { name: 'Smart Home Lighting' },
      { name: 'Smart Locks and Entry' },
      { name: 'Security Cameras and Systems' },
      { name: 'Plugs and Outlets' },
      { name: 'New Smart Devices' },
      { name: 'Heating and Cooling' },
      { name: 'Detectors and Sensors' },
      { name: 'Home Entertainment' },
      { name: 'Pet' },
      { name: 'Voice Assistants and Hubs' },
      { name: 'Kitchen' },
      { name: 'Vacuums and Mops' },
      { name: 'Lawn and Garden' },
      { name: 'WIFI and Networking' },
      { name: 'Other Solutions' },
    ],
  },
  {
    name: 'Arts & Crafts',
    subcategories: [
      { name: 'Painting, Drawing & Art Supplies' },
      { name: 'Beading & Jewelry Making' },
      { name: 'Crafting' },
      { name: 'Fabric' },
      { name: 'Fabric Decorating' },
      { name: 'Knitting & Crochet' },
      { name: 'Needlework' },
      { name: 'Organization, Storage & Transport' },
      { name: 'Printmaking' },
      { name: 'Scrapbooking & Stamping' },
      { name: 'Sewing' },
      { name: 'Party Decorations & Supplies' },
      { name: 'Gift Wrapping Supplies' },
    ],
  },
  {
    name: 'Automotive',
    subcategories: [
      { name: 'Car Care' },
      { name: 'Car Electronics & Accessories' },
      { name: 'Exterior Accessories' },
      { name: 'Interior Accessories' },
      { name: 'Lights & Lighting Accessories' },
      { name: 'Motorcycle & Powersports' },
      { name: 'Oils & Fluids' },
      { name: 'Paint & Paint Supplies' },
      { name: 'Performance Parts & Accessories' },
      { name: 'Replacement Parts' },
      { name: 'RV Parts & Accessories' },
      { name: 'Tires & Wheels' },
      { name: 'Tools & Equipment' },
      { name: 'Automotive Enthusiast Merchandise' },
      { name: 'Heavy Duty & Commercial Vehicle Equipment' },
    ],
  },
  {
    name: 'Baby',
    subcategories: [
      { name: 'Activity & Entertainment' },
      { name: 'Apparel & Accessories' },
      { name: 'Baby & Toddler Toys' },
      { name: 'Baby Care' },
      { name: 'Baby Stationery' },
      { name: 'Car Seats & Accessories' },
      { name: 'Diapering' },
      { name: 'Feeding' },
      { name: 'Gifts' },
      { name: 'Nursery' },
      { name: 'Potty Training' },
      { name: 'Pregnancy & Maternity' },
      { name: 'Safety' },
      { name: 'Strollers & Accessories' },
      { name: 'Travel Gear' },
    ],
  },
  {
    name: 'Beauty and Personal Care',
    subcategories: [
      { name: 'Makeup' },
      { name: 'Skin Care' },
      { name: 'Hair Care' },
      { name: 'Fragrance' },
      { name: 'Foot, Hand & Nail Care' },
      { name: 'Tools & Accessories' },
      { name: 'Shave & Hair Removal' },
      { name: 'Personal Care' },
      { name: 'Oral Care' },
    ],
  },
  {
    name: "Women's Fashion",
    subcategories: [
      { name: 'Clothing' },
      { name: 'Shoes' },
      { name: 'Jewelry' },
      { name: 'Watches' },
      { name: 'Handbags' },
      { name: 'Accessories' },
    ],
  },
  {
    name: "Men's Fashion",
    subcategories: [
      { name: 'Clothing' },
      { name: 'Shoes' },
      { name: 'Watches' },
      { name: 'Accessories' },
    ],
  },
  {
    name: "Girls' Fashion",
    subcategories: [
      { name: 'Clothing' },
      { name: 'Shoes' },
      { name: 'Jewelry' },
      { name: 'Watches' },
      { name: 'Accessories' },
      { name: 'School Uniforms' },
    ],
  },
  {
    name: "Boys' Fashion",
    subcategories: [
      { name: 'Clothing' },
      { name: 'Shoes' },
      { name: 'Jewelry' },
      { name: 'Watches' },
      { name: 'Accessories' },
      { name: 'School Uniforms' },
    ],
  },
  {
    name: 'Health and Household',
    subcategories: [
      { name: 'Baby & Child Care' },
      { name: 'Health Care' },
      { name: 'Household Supplies' },
      { name: 'Medical Supplies & Equipment' },
      { name: 'Oral Care' },
      { name: 'Personal Care' },
      { name: 'Sexual Wellness' },
      { name: 'Sports Nutrition' },
      { name: 'Stationery & Gift Wrapping Supplies' },
      { name: 'Vision Care' },
      { name: 'Vitamins & Dietary Supplements' },
      { name: 'Wellness & Relaxation' },
    ],
  },
  {
    name: 'Home and Kitchen',
    subcategories: [
      { name: "Kids' Home Store" },
      { name: 'Kitchen & Dining' },
      { name: 'Bedding' },
      { name: 'Bath' },
      { name: 'Furniture' },
      { name: 'Home Décor' },
      { name: 'Wall Art' },
      { name: 'Lighting & Ceiling Fans' },
      { name: 'Seasonal Décor' },
      { name: 'Event & Party Supplies' },
      { name: 'Heating, Cooling & Air Quality' },
      { name: 'Irons & Steamers' },
      { name: 'Vacuums & Floor Care' },
      { name: 'Storage & Organization' },
      { name: 'Cleaning Supplies' },
    ],
  },
  {
    name: 'Industrial and Scientific',
    subcategories: [
      { name: 'Abrasive & Finishing Products' },
      { name: 'Additive Manufacturing Products' },
      { name: 'Commercial Door Products' },
      { name: 'Cutting Tools' },
      { name: 'Fasteners' },
      { name: 'Filtration' },
      { name: 'Food Service Equipment & Supplies' },
      { name: 'Hydraulics, Pneumatics & Plumbing' },
      { name: 'Industrial Electrical' },
      { name: 'Industrial Hardware' },
      { name: 'Industrial Power & Hand Tools' },
      { name: 'Janitorial & Sanitation Supplies' },
      { name: 'Lab & Scientific Products' },
      { name: 'Material Handling Products' },
      { name: 'Occupational Health & Safety Products' },
      { name: 'Packaging & Shipping Supplies' },
      { name: 'Power Transmission Products' },
      { name: 'Professional Dental Supplies' },
      { name: 'Professional Medical Supplies' },
      { name: 'Raw Materials' },
      { name: 'Retail Store Fixtures & Equipment' },
      { name: 'Robotics' },
      { name: 'Science Education' },
      { name: 'Tapes, Adhesives & Sealants' },
      { name: 'Test, Measure & Inspect' },
    ],
  },
  {
    name: 'Luggage',
    subcategories: [
      { name: 'Carry-ons' },
      { name: 'Backpacks' },
      { name: 'Garment bags' },
      { name: 'Travel Totes' },
      { name: 'Luggage Sets' },
      { name: 'Laptop Bags' },
      { name: 'Suitcases' },
      { name: 'Kids Luggage' },
      { name: 'Messenger Bags' },
      { name: 'Umbrellas' },
      { name: 'Duffles' },
      { name: 'Travel Accessories' },
    ],
  },
  {
    name: 'Movies & Television',
    subcategories: [
      { name: 'Movies' },
      { name: 'TV Shows' },
      { name: 'Blu-ray' },
      { name: '4K Ultra HD' },
      { name: 'Best Sellers' },
      { name: "Today's Deals" },
      { name: 'New Releases' },
      { name: 'Pre-orders' },
      { name: 'Kids & Family' },
      { name: 'Prime Video' },
    ],
  },
  {
    name: 'Pet Supplies',
    subcategories: [
      { name: 'Dogs' },
      { name: 'Cats' },
      { name: 'Fish & Aquatic Pets' },
      { name: 'Birds' },
      { name: 'Horses' },
      { name: 'Reptiles & Amphibians' },
      { name: 'Small Animals' },
    ],
  },
  {
    name: 'Software',
    subcategories: [
      { name: 'Accounting & Finance' },
      { name: 'Antivirus & Security' },
      { name: 'Business & Office' },
      { name: "Children's" },
      { name: 'Design & Illustration' },
      { name: 'Digital Software' },
      { name: 'Education & Reference' },
      { name: 'Games' },
      { name: 'Lifestyle & Hobbies' },
      { name: 'Music' },
      { name: 'Networking & Servers' },
      { name: 'Operating Systems' },
      { name: 'Photography' },
      { name: 'Programming & Web Development' },
      { name: 'Tax Preparation' },
      { name: 'Utilities' },
      { name: 'Video' },
    ],
  },
  {
    name: 'Sports and Outdoors',
    subcategories: [
      { name: 'Sports and Outdoors' },
      { name: 'Outdoor Recreation' },
      { name: 'Sports & Fitness' },
    ],
  },
  {
    name: 'Tools & Home Improvement',
    subcategories: [
      { name: 'Tools & Home Improvement' },
      { name: 'Appliances' },
      { name: 'Building Supplies' },
      { name: 'Electrical' },
      { name: 'Hardware' },
      { name: 'Kitchen & Bath Fixtures' },
      { name: 'Light Bulbs' },
      { name: 'Lighting & Ceiling Fans' },
      { name: 'Measuring & Layout Tools' },
      { name: 'Painting Supplies & Wall Treatments' },
      { name: 'Power & Hand Tools' },
      { name: 'Rough Plumbing' },
      { name: 'Safety & Security' },
      { name: 'Storage & Home Organization' },
      { name: 'Welding & Soldering' },
    ],
  },
  {
    name: 'Toys and Games',
    subcategories: [
      { name: 'Action Figures & Statues' },
      { name: 'Arts & Crafts' },
      { name: 'Baby & Toddler Toys' },
      { name: 'Building Toys' },
      { name: 'Dolls & Accessories' },
      { name: 'Dress Up & Pretend Play' },
      { name: "Kids' Electronics" },
      { name: 'Games' },
      { name: 'Grown-Up Toys' },
      { name: 'Hobbies' },
      { name: "Kids' Furniture, Décor & Storage" },
      { name: 'Learning & Education' },
      { name: 'Novelty & Gag Toys' },
      { name: 'Party Supplies' },
      { name: 'Puppets' },
      { name: 'Puzzles' },
      { name: 'Sports & Outdoor Play' },
      { name: 'Stuffed Animals & Plush Toys' },
      { name: 'Toy Remote Control & Play Vehicles' },
      { name: 'Tricycles, Scooters & Wagons' },
      { name: 'Video Games' },
    ],
  },
  {
    name: 'Video Games',
    subcategories: [
      { name: 'Video Games' },
      { name: 'PlayStation 4' },
      { name: 'PlayStation 3' },
      { name: 'Xbox One' },
      { name: 'Xbox 360' },
      { name: 'Nintendo Switch' },
      { name: 'Wii U' },
      { name: 'Wii' },
      { name: 'PC' },
      { name: 'Mac' },
      { name: 'Nintendo 3DS & 2DS' },
      { name: 'Nintendo DS' },
      { name: 'PlayStation Vita' },
      { name: 'Sony PSP' },
      { name: 'Retro Gaming & Microconsoles' },
      { name: 'Accessories' },
      { name: 'Digital Games' },
      { name: 'Kids & Family' },
    ],
  },
];
