export const productAttributesJson = [
  {
    name: 'Color',
    values: [
      { name: 'Red', value: '#FF0000' },
      { name: 'Blue', value: '#0000FF' },
      { name: 'Green', value: '#00FF00' },
      { name: 'Black', value: '#000000' },
      { name: 'White', value: '#FFFFFF' },
      { name: 'Yellow', value: '#FFFF00' },
      { name: 'Pink', value: '#FFC0CB' },
      { name: 'Purple', value: '#800080' },
      { name: 'Orange', value: '#FFA500' },
      { name: 'Gray', value: '#808080' },
      { name: 'Brown', value: '#A52A2A' },
      { name: 'Navy', value: '#000080' },
    ],
  },
  {
    name: 'Size',
    values: [
      { name: 'Extra Small', value: 'XS' },
      { name: 'Small', value: 'S' },
      { name: 'Medium', value: 'M' },
      { name: 'Large', value: 'L' },
      { name: 'Extra Large', value: 'XL' },
      { name: 'Double Extra Large', value: 'XXL' },
      { name: 'Triple Extra Large', value: 'XXXL' },
    ],
  },
  {
    name: 'Material',
    values: [
      { name: 'Cotton', value: 'cotton' },
      { name: 'Polyester', value: 'polyester' },
      { name: 'Wool', value: 'wool' },
      { name: 'Silk', value: 'silk' },
      { name: 'Linen', value: 'linen' },
      { name: 'Leather', value: 'leather' },
      { name: 'Denim', value: 'denim' },
      { name: 'Velvet', value: 'velvet' },
      { name: 'Rayon', value: 'rayon' },
      { name: 'Spandex', value: 'spandex' },
    ],
  },
  {
    name: 'Style',
    values: [
      { name: 'Casual', value: 'casual' },
      { name: 'Formal', value: 'formal' },
      { name: 'Sport', value: 'sport' },
      { name: 'Business', value: 'business' },
      { name: 'Outdoor', value: 'outdoor' },
      { name: 'Athletic', value: 'athletic' },
      { name: 'Vintage', value: 'vintage' },
      { name: 'Bohemian', value: 'bohemian' },
      { name: 'Streetwear', value: 'streetwear' },
      { name: 'Luxury', value: 'luxury' },
    ],
  },
  {
    name: 'Pattern',
    values: [
      { name: 'Solid', value: 'solid' },
      { name: 'Striped', value: 'striped' },
      { name: 'Checked', value: 'checked' },
      { name: 'Polka Dot', value: 'polka_dot' },
      { name: 'Floral', value: 'floral' },
      { name: 'Animal Print', value: 'animal_print' },
      { name: 'Paisley', value: 'paisley' },
      { name: 'Geometric', value: 'geometric' },
      { name: 'Camouflage', value: 'camouflage' },
      { name: 'Abstract', value: 'abstract' },
    ],
  },
  {
    name: 'Fit',
    values: [
      { name: 'Slim', value: 'slim' },
      { name: 'Regular', value: 'regular' },
      { name: 'Loose', value: 'loose' },
      { name: 'Oversized', value: 'oversized' },
      { name: 'Tailored', value: 'tailored' },
      { name: 'Relaxed', value: 'relaxed' },
    ],
  },
  {
    name: 'Length',
    values: [
      { name: 'Short', value: 'short' },
      { name: 'Knee-Length', value: 'knee_length' },
      { name: 'Ankle-Length', value: 'ankle_length' },
      { name: 'Full-Length', value: 'full_length' },
      { name: 'Three-Quarter', value: 'three_quarter' },
      { name: 'Crop', value: 'crop' },
    ],
  },
  {
    name: 'Season',
    values: [
      { name: 'Spring', value: 'spring' },
      { name: 'Summer', value: 'summer' },
      { name: 'Fall', value: 'fall' },
      { name: 'Winter', value: 'winter' },
    ],
  },
  {
    name: 'Sleeve Length',
    values: [
      { name: 'Sleeveless', value: 'sleeveless' },
      { name: 'Short Sleeve', value: 'short_sleeve' },
      { name: 'Three Quarter Sleeve', value: 'three_quarter_sleeve' },
      { name: 'Long Sleeve', value: 'long_sleeve' },
    ],
  },
  {
    name: 'Neckline',
    values: [
      { name: 'V-Neck', value: 'v_neck' },
      { name: 'Round Neck', value: 'round_neck' },
      { name: 'Collar', value: 'collar' },
      { name: 'Turtleneck', value: 'turtleneck' },
      { name: 'Off-Shoulder', value: 'off_shoulder' },
      { name: 'Boat Neck', value: 'boat_neck' },
    ],
  },
  {
    name: 'Closure',
    values: [
      { name: 'Button', value: 'button' },
      { name: 'Zipper', value: 'zipper' },
      { name: 'Pullover', value: 'pullover' },
      { name: 'Tie', value: 'tie' },
      { name: 'Velcro', value: 'velcro' },
      { name: 'Buckle', value: 'buckle' },
    ],
  },
];
