export const productAttributesJson = [
  {
    name: 'Color',
    id: 1,
    values: [
      { id: 100, name: 'Red', value: '#FF0000' },
      { id: 101, name: 'Blue', value: '#0000FF' },
      { id: 102, name: 'Green', value: '#00FF00' },
      { id: 103, name: 'Black', value: '#000000' },
      { id: 104, name: 'White', value: '#FFFFFF' },
      { id: 105, name: 'Yellow', value: '#FFFF00' },
      { id: 106, name: 'Pink', value: '#FFC0CB' },
      { id: 107, name: 'Purple', value: '#800080' },
      { id: 108, name: 'Orange', value: '#FFA500' },
      { id: 109, name: 'Gray', value: '#808080' },
      { id: 110, name: 'Brown', value: '#A52A2A' },
      { id: 111, name: 'Navy', value: '#000080' },
    ],
  },
  {
    name: 'Size',
    id: 2,
    values: [
      { id: 200, name: 'Extra Small', value: 'XS' },
      { id: 201, name: 'Small', value: 'S' },
      { id: 202, name: 'Medium', value: 'M' },
      { id: 203, name: 'Large', value: 'L' },
      { id: 204, name: 'Extra Large', value: 'XL' },
      { id: 205, name: 'Double Extra Large', value: 'XXL' },
      { id: 206, name: 'Triple Extra Large', value: 'XXXL' },
    ],
  },
  {
    name: 'Material',
    id: 300,
    values: [
      { id: 300, name: 'Cotton', value: 'cotton' },
      { id: 301, name: 'Polyester', value: 'polyester' },
      { id: 302, name: 'Wool', value: 'wool' },
      { id: 303, name: 'Silk', value: 'silk' },
      { id: 304, name: 'Linen', value: 'linen' },
      { id: 305, name: 'Leather', value: 'leather' },
      { id: 306, name: 'Denim', value: 'denim' },
      { id: 307, name: 'Velvet', value: 'velvet' },
      { id: 308, name: 'Rayon', value: 'rayon' },
      { id: 309, name: 'Spandex', value: 'spandex' },
    ],
  },
  {
    name: 'Style',
    id: 400,
    values: [
      { id: 400, name: 'Casual', value: 'casual' },
      { id: 401, name: 'Formal', value: 'formal' },
      { id: 402, name: 'Sport', value: 'sport' },
      { id: 403, name: 'Business', value: 'business' },
      { id: 404, name: 'Outdoor', value: 'outdoor' },
      { id: 405, name: 'Athletic', value: 'athletic' },
      { id: 406, name: 'Vintage', value: 'vintage' },
      { id: 407, name: 'Bohemian', value: 'bohemian' },
      { id: 408, name: 'Streetwear', value: 'streetwear' },
      { id: 409, name: 'Luxury', value: 'luxury' },
    ],
  },
  {
    name: 'Pattern',
    id: 500,
    values: [
      { id: 500, name: 'Solid', value: 'solid' },
      { id: 501, name: 'Striped', value: 'striped' },
      { id: 502, name: 'Checked', value: 'checked' },
      { id: 503, name: 'Polka Dot', value: 'polka_dot' },
      { id: 504, name: 'Floral', value: 'floral' },
      { id: 505, name: 'Animal Print', value: 'animal_print' },
      { id: 506, name: 'Paisley', value: 'paisley' },
      { id: 507, name: 'Geometric', value: 'geometric' },
      { id: 508, name: 'Camouflage', value: 'camouflage' },
      { id: 509, name: 'Abstract', value: 'abstract' },
    ],
  },
  {
    name: 'Fit',
    id: 600,
    values: [
      { id: 600, name: 'Slim', value: 'slim' },
      { id: 601, name: 'Regular', value: 'regular' },
      { id: 602, name: 'Loose', value: 'loose' },
      { id: 603, name: 'Oversized', value: 'oversized' },
      { id: 604, name: 'Tailored', value: 'tailored' },
      { id: 605, name: 'Relaxed', value: 'relaxed' },
    ],
  },

  {
    name: 'Length',
    id: 700,
    values: [
      { id: 700, name: 'Short', value: 'short' },
      { id: 701, name: 'Knee-Length', value: 'knee_length' },
      { id: 702, name: 'Ankle-Length', value: 'ankle_length' },
      { id: 703, name: 'Full-Length', value: 'full_length' },
      { id: 704, name: 'Three-Quarter', value: 'three_quarter' },
      { id: 705, name: 'Crop', value: 'crop' },
    ],
  },
  {
    name: 'Season',
    id: 800,
    values: [
      { id: 800, name: 'Spring', value: 'spring' },
      { id: 801, name: 'Summer', value: 'summer' },
      { id: 802, name: 'Fall', value: 'fall' },
      { id: 803, name: 'Winter', value: 'winter' },
    ],
  },
  {
    name: 'Sleeve Length',
    id: 900,
    values: [
      { id: 900, name: 'Sleeveless', value: 'sleeveless' },
      { id: 901, name: 'Short Sleeve', value: 'short_sleeve' },
      { id: 902, name: 'Three Quarter Sleeve', value: 'three_quarter_sleeve' },
      { id: 903, name: 'Long Sleeve', value: 'long_sleeve' },
    ],
  },
  {
    name: 'Neckline',
    id: 1000,
    values: [
      { id: 1000, name: 'V-Neck', value: 'v_neck' },
      { id: 1001, name: 'Round Neck', value: 'round_neck' },
      { id: 1002, name: 'Collar', value: 'collar' },
      { id: 1003, name: 'Turtleneck', value: 'turtleneck' },
      { id: 1004, name: 'Off-Shoulder', value: 'off_shoulder' },
      { id: 1005, name: 'Boat Neck', value: 'boat_neck' },
    ],
  },
  {
    name: 'Closure',
    id: 1100,
    values: [
      { id: 1100, name: 'Button', value: 'button' },
      { id: 1101, name: 'Zipper', value: 'zipper' },
      { id: 1102, name: 'Pullover', value: 'pullover' },
      { id: 1103, name: 'Tie', value: 'tie' },
      { id: 1104, name: 'Velcro', value: 'velcro' },
      { id: 1105, name: 'Buckle', value: 'buckle' },
    ],
  },
];
